"""create job description and job requirement tables

Revision ID: 2badee0172d6
Revises: 0f9ff0d35f97
Create Date: 2026-07-11 18:19:36.999932

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2badee0172d6'
down_revision: str | Sequence[str] | None = '0f9ff0d35f97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('importance', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requirements')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
