"""create resume versions table

Revision ID: 3d4d3676498a
Revises: 9f7a5a776b1f
Create Date: 2026-07-12 13:17:45.857880

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d4d3676498a'
down_revision: str | Sequence[str] | None = '9f7a5a776b1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('match_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('applied_suggestion_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['match_analysis_id'], ['match_analyses.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_versions')
    # ### end Alembic commands ###
