"""create resume suggestions table

Revision ID: 9f7a5a776b1f
Revises: d14b85b9f7c1
Create Date: 2026-07-11 20:43:17.298436

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f7a5a776b1f'
down_revision: str | Sequence[str] | None = 'd14b85b9f7c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_match_id', sa.Uuid(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('suggested_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_grounded', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_match_id'], ['requirement_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_suggestions')
    # ### end Alembic commands ###
