"""add embedding column to candidate evidence

Revision ID: b8de7e54b1de
Revises: 2badee0172d6
Create Date: 2026-07-11 18:33:17.180922

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8de7e54b1de'
down_revision: str | Sequence[str] | None = '2badee0172d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column(
        'candidate_evidence',
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_evidence', 'embedding')
    # ### end Alembic commands ###
