"""create match analysis and requirement match tables

Revision ID: d14b85b9f7c1
Revises: b8de7e54b1de
Create Date: 2026-07-11 20:23:31.869700

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd14b85b9f7c1'
down_revision: str | Sequence[str] | None = 'b8de7e54b1de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('job_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ),
    sa.ForeignKeyConstraint(['match_analysis_id'], ['match_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_matches')
    op.drop_table('match_analyses')
    # ### end Alembic commands ###
